.text
.p2align 5
.globl _CRYPTO_NAMESPACE(sc25519_sub_nored)
.globl CRYPTO_NAMESPACE(sc25519_sub_nored)
_CRYPTO_NAMESPACE(sc25519_sub_nored):
CRYPTO_NAMESPACE(sc25519_sub_nored):
mov %rsp,%r11
and $31,%r11
add $0,%r11
sub %r11,%rsp
movq   0(%rsi),%rcx
movq   8(%rsi),%r8
movq   16(%rsi),%r9
movq   24(%rsi),%rsi
subq 0(%rdx),%rcx
sbbq 8(%rdx),%r8
sbbq 16(%rdx),%r9
sbbq 24(%rdx),%rsi
movq   %rcx,0(%rdi)
movq   %r8,8(%rdi)
movq   %r9,16(%rdi)
movq   %rsi,24(%rdi)
add %r11,%rsp
mov %rdi,%rax
mov %rsi,%rdx
ret

.type _CRYPTO_NAMESPACE(sc25519_sub_nored), @function
.size _CRYPTO_NAMESPACE(sc25519_sub_nored), . - _CRYPTO_NAMESPACE(sc25519_sub_nored)
.type CRYPTO_NAMESPACE(sc25519_sub_nored), @function
.size CRYPTO_NAMESPACE(sc25519_sub_nored), . - CRYPTO_NAMESPACE(sc25519_sub_nored)

.section	.note.GNU-stack,"",@progbits